### ISSUE TITLE
Licensing on materials created at the event

### ISSUE THREAD

**Issue by billymeinke** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#10]
I'd like to start a discussion about which copyright license or marking is applied to the materials coming out of this event, and submit my recommendation:

CC0 Public Domain Dedication, with a request for attribution.
http://creativecommons.org/publicdomain/zero/1.0/

Happy to discuss.

**Comment by hlapp** [comment]
This was accepted.
