### ISSUE TITLE
Computer setup, in preparation for reproducible science

### ISSUE THREAD

**Issue by kbroman** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#16]
A common issue is helping people setup their laptop (or other computer) as they seek to adopt a reproducible research workflow.

The [Software Carpentry instructions](http://software-carpentry.org/v5/setup.html) are great, but some aspects (e.g., [gitbash](http://msysgit.github.io/)) seem a bit too short-term. I generally recommend that Windows users install [cygwin](https://www.cygwin.com/), but maybe I'm wrong to do so.

**Comment by hlapp** [comment]
Meanwhile there are instructions on the workshop website(s), for example [here for the iDigBio one](http://reproducible-science-curriculum.github.io/2015-06-01-reproducible-science-idigbio/#setup).
