### ISSUE TITLE
Organize Intro (group 1) sprint

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#19]
- [x] ask Mine if she will lead
- [x] send out Doodle poll
- [x] set time (and update this ticket with time)
- [x] add people to README (see Reproducible-Science-Curriculum/rr-intro#3)

**Comment by hlapp** [comment]
@mine-cetinkaya-rundel will lead.

**Comment by hlapp** [comment]
I think this group is well underway. @mine-cetinkaya-rundel let us know if not.
