### ISSUE TITLE
Organize Process I (group 2) sprint

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#20]
- [x] determine who will lead
- [x] send out Doodle poll
- [x] pick time and update this ticket with time
- [x] add people to README (see Reproducible-Science-Curriculum/rr-organization1#2)

**Comment by iamciera** [comment]
I will lead this group.  We may not be able to do a sprint time. But we are setting up a meeting time to talk about how to finish everything.  I will keep updating here.

**Comment by hlapp** [comment]
:+1: @iamciera ! Thanks for stepping up!

**Comment by hlapp** [comment]
According to @iamciera:

>  We are not having a sprint, but are working together to finish everything by April 10. 

I checked off the "pick time" task as superseded, and date is set to April 10.
