### ISSUE TITLE
Organize Process II (group 3) sprint

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#21]
- [ ] determine who will lead
- [ ]  send out Doodle poll
- [ ] pick time (and update this issue with time)
- [ ] add people to README (see Reproducible-Science-Curriculum/rr-multifile#3)

**Comment by hlapp** [comment]
[Organization / Process II](http://github.com/Reproducible-Science-Curriculum/rr-multifile) is currently orphaned. I am closing this therefore for now; it can be re-opened once someone steps forward.
