### ISSUE TITLE
Organize Automation (group 4) sprint

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#23]
- [x] determine who will lead
- [x] send out Doodle poll
- [x] pick time (and update this issue with time)
- [x] add people to README (see Reproducible-Science-Curriculum/rr-automation#1)

**Comment by hlapp** [comment]
@fmichonneau will lead.

**Comment by hlapp** [comment]
This group is also well underway, I think. @fmichonneau let us know if not, but I'll close this for now.
