### ISSUE TITLE
Inaugural workshop set for May 14-15 at Duke, need instructors

### ISSUE THREAD

**Issue by hlapp** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#25]
The dates and place for the first workshop to be taught using the curriculum has been set.  It is May 14-15 in the Workshop room in [Duke Library's new EDGE space](http://library.duke.edu/edge).

We need to confirm instructors for each lesson as well as helpers. So far I have Mine and myself down for the Intro and Publication lessons, respectively. This means 
* Organization I, 
* Organization II, and 
* Automation

still need instructor commitments. We can also use more helpers, and as SWC/DC experience shows, should have at least two there who would next teach elsewhere. Please contact me if you would be interested and are likely to be teaching a future workshop. We have support for instructor travel, so travel costs should not be a hindrance.

I have created a repository for the inaugural workshop: https://github.com/Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke Ultimately this will hold the website, but for now we can use the issue tracker and wiki there for workshop-specific communication.

**Comment by mine-cetinkaya-rundel** [comment]
Are we open to helpers who weren't part of the original hackathon? If so, I might be able to recruit someone to help Into, and potentially some others as well.

**Comment by hlapp** [comment]
Tracker item for listing instructors and helpers: Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke#1

Please edit/add.

**Comment by hlapp** [comment]
Instructors and helpers set. Organization II is removed from the curriculum.
