### ISSUE TITLE
Need lesson synopses for inaugural workshop website and registration

### ISSUE THREAD

**Issue by hlapp** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#26]
We need to get the registration site and a rudimentary website up for the [May 14-15 workshop at Duke](https://github.com/Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke), for which we'll need a 1-3 sentence synopsis for each lesson. Perhaps each lesson team could work on articulating what that should be, and put it here:

https://github.com/Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke/wiki/Lesson-synopses

Putting them in the respective lesson repos' README files would be fine with me too.

**Comment by naupaka** [comment]
Just added a few sentences for the organization group.

**Comment by hlapp** [comment]
Can be considered done, though @kcranston's work during the Sep 2015 development sprint (Reproducible-Science-Curriculum/planning#1) may add to or refactor this.
