### ISSUE TITLE
Reproducible research checklist

### ISSUE THREAD

**Issue by pschloss** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#27]
As part of the introduction group, I tried my hand at creating a first draft of a checklist that would be given to participants. It builds off of @billymeinke pulled together for the ropensci conference (http://ropensci.github.io/reproducibility-guide/sections/checklist/) and the things we talked about at the meeting.

I tried to put this into a grid with good/better/best column headings, but it was too hard to think about that way. I purposefully shot for the best practice for each of these items. As I state in the header, the goal isn't a bunch of "Yes" responses, but to get people to think about how they can do better.

**Comment by hlapp** [comment]
The checklist is meanwhile in the [rr-intro repo](https://github.com/Reproducible-Science-Curriculum/rr-intro) (as per Reproducible-Science-Curriculum/rr-intro@dbcefc90150ba43872dd8eb97771764f7e1d77b1), and apparently also duplicated in the workshop websites (for example the [one for the iDigBio workshop](http://reproducible-science-curriculum.github.io/2015-06-01-reproducible-science-idigbio/checklist.html).
