### ISSUE TITLE
Open Source Software

### ISSUE THREAD

**Issue by dmlond** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#4]
We should include a general introduction to the concepts and practices involved in releasing software to the world with Open Source Licenses.  This would discuss some or all of the following:
* a discussion of software licenses
* intro to git
* intro to github
* intro to the docker registry
* ways that github and the docker registry can be hooked together
* [keybase](https://keybase.io/)
* [zenodo](http://zenodo.org/) DOIs for reproducible analysis source code hosted on github

**Comment by hlapp** [comment]
Another one is this: Halchenko, Yaroslav O., and Michael Hanke. 2015. “[Four Aspects to Make Science Open ‘by Design’ and Not as an after-Thought.](http://dx.doi.org/10.1186/s13742-015-0072-7)” GigaScience 4 (July): 31.
